{% set version = "0.3.0" %}

package:
  name: seurat-scripts
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/r-seurat-scripts/archive/{{ version }}.tar.gz
  sha256: bcc171d7b381df7261c90aaac5f78436ba42b2fe0b32e625504c6ed6cdadf21a

build:
  number: 0
  noarch: generic

requirements:
    host:
        - r-base
    run:
        - r-seurat <3.2.0
        - r-optparse
        - r-workflowscriptscommon >=0.0.6,<=0.0.7
        - r-loom
        - r-cairo
        - bioconductor-scater
        - libpng
        - mscorefonts

test:
    commands:
        - seurat-read-10x.R --help
        - seurat-normalise-data.R --help
        - seurat-filter-cells.R --help
        - seurat-find-variable-genes.R --help
        - seurat-run-pca.R --help
        - seurat-scale-data.R --help
        - seurat-dim-plot.R --help
        - seurat-find-clusters.R --help
        - seurat-run-tsne.R --help
        - seurat-find-markers.R --help
        - seurat-export-cellbrowser.R --help
        - seurat-find-neighbours.R --help
        - which seurat-get-random-genes.R
        - which r-seurat-scripts-post-install-tests.sh

about:
  home: https://github.com/ebi-gene-expression-group/r-seurat-scripts
  dev_url: https://github.com/ebi-gene-expression-group/r-seurat-scripts
  license: Apache-2.0
  summary: A set of wrappers for individual components of the Seurat package.
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - pcm32
    - pinin4fjords
    - nh3
